services:
  - type: web
    name: ferremas-frontend
    env: node
    plan: free
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_BASE_URL
        value: https://your-api-url.onrender.com/api  # Replace with your API URL
    staticPublishPath: ./dist